// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Child", b =>
                {
                    b.Property<int>("childId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("personId")
                        .HasColumnType("int");

                    b.HasKey("childId");

                    b.HasIndex("personId");

                    b.ToTable("children");
                });

            modelBuilder.Entity("DAL.Person", b =>
                {
                    b.Property<int>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("helth")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("personId");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("DAL.Child", b =>
                {
                    b.HasOne("DAL.Person", null)
                        .WithMany("child")
                        .HasForeignKey("personId");
                });

            modelBuilder.Entity("DAL.Person", b =>
                {
                    b.Navigation("child");
                });
#pragma warning restore 612, 618
        }
    }
}
